### ISSUE TITLE
Name confict with X11 for 'None'

### ISSUE THREAD

**Issue by subh83** [jbeder/yaml-cpp#320]
Line 115 of X11/X.h defines the following:
`#define None 0L`

Line 10 of yaml-cpp/emitterdef.h has:
`... enum value { None, Property, ...`

Thus, if X11 is included before including yaml-cpp, a compilation error "expected identifier before numeric constant" is thrown. This may actually be something that needs to be fixed in X11 rather than yaml-cpp.

**Comment by jbeder** [comment]
Yeah, this is definitely an X11 issue. Can you file a bug against them? I might still do something here, but it'd be nice if they could fix their issue.

**Comment by Delwin9999** [comment]
yaml-cpp/include/yaml-cpp/node/detail/node_iterator.h:21 also has this issue.

**Comment by Delwin9999** [comment]
CImg also has a #define None 0 so this is getting more difficult to handle.  It's a simple enough rename on yaml-cpp's end to just get out of the way.  Any chance we could see that soon?

**Comment by vks** [comment]
I believe this is already fixed. It seems like this issue can be closed.
https://github.com/jbeder/yaml-cpp/blob/master/include/yaml-cpp/emitterdef.h

**Comment by cybel** [comment]
Problem still exists, and unfortunately this is a killer bug since X11 isn't optional in my situation (and keeping them apart is an excessive chore for my needs). I might try to throw together a patch and push it if such a fix is considerable, since trying to interop with legacy C code might not be in the purview of the project. 

https://github.com/jbeder/yaml-cpp/blob/master/include/yaml-cpp/node/detail/node_iterator.h#L22
